#:schema node_modules/wrangler/config-schema.json
name = "twikoo-cloudflare"
main = "src/index.js"
compatibility_date = "2024-05-02"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "958824b7-8a5c-42c5-82a6-428975db06cb"

[vars]
IS_CLOUDFLARE_WORKER = "true"

[dev]
port = 5000
